name: linOS 2404 g++ Max Flash

on:
  workflow_dispatch:
  push:
    branches: [test, test-linos, test-max, test-flash, test-linos-max, test-linos-flash, test-max-flash, test-linos-max-flash]

jobs:
  build:
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v5

      - name: g++ Alter
        uses: ./.github/actions/gxx-alter
        with:
          alter_version: 14

      - name: Configs
        uses: ./.github/actions/configs

      - name: Builder
        uses: ./.github/actions/builder

      - name: Testing
        uses: ./.github/actions/testing