name: Windows 2025 MSVC Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-2025
    steps:
      - name: Checkout code
        uses: actions/checkout@v5

      - name: Setup MSVC environment
        uses: ilammy/msvc-dev-cmd@v1

      - name: Show cl version
        run: cl

      - name: Configure CMake
        run: cmake -S . -B build -G "Ninja" -DCMAKE_BUILD_TYPE=Release

      - name: Build
        run: cmake --build build